/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author TEACHER
 */
public class UpdateAnAcc extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAnAcc
     */
    public UpdateAnAcc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel1.setText("UPDATE AN ACCOUNT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 11, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));
        jPanel5.setLayout(null);

        jLabel5.setText("Customer Type :-");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(37, 40, 120, 14);

        jCheckBox3.setText("Public");
        jPanel5.add(jCheckBox3);
        jCheckBox3.setBounds(170, 40, 80, 23);

        jCheckBox4.setText("Staff");
        jPanel5.add(jCheckBox4);
        jCheckBox4.setBounds(240, 40, 70, 23);

        jLabel6.setText("Name of Holder :-");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(38, 69, 100, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(138, 70, 250, 30);

        jLabel7.setText("Gender :-");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(40, 110, 60, 14);

        jRadioButton3.setText("Male");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Female");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton4)
                .addComponent(jRadioButton3))
        );

        jPanel5.add(jPanel4);
        jPanel4.setBounds(170, 110, 150, 20);

        jLabel8.setText("Name of father :-");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 150, 100, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3);
        jTextField3.setBounds(140, 140, 250, 30);

        jLabel9.setText("Name of Mother :-");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(40, 200, 88, 14);
        jPanel5.add(jTextField4);
        jTextField4.setBounds(140, 190, 250, 30);

        jLabel10.setText("Date of Birth :-");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(40, 250, 90, 14);
        jPanel5.add(jTextField5);
        jTextField5.setBounds(140, 240, 250, 30);

        jLabel11.setText("Marital Information :-");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(40, 300, 120, 20);

        jLabel12.setText("Nationality :-");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(40, 360, 90, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indian", "American", "Russian", "Korian", "Mexican", "Italian", "German", "Sri Lankan", "Bangladeshi", "Nepalian", "Pakistan", "Other" }));
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(150, 350, 110, 40);

        jRadioButton5.setText("Married");

        jRadioButton6.setText("Unmarried");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(170, 300, 190, 20);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 172, 416, 430));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Account", "Saving Account", "Recurring Account", "Fixed Deposit Account" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 113, 138, 41));

        jLabel14.setText("Choose Account Type :-");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 124, 130, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jPanel7.setLayout(null);

        jLabel2.setText("Local Address :-");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(30, 30, 120, 14);

        jLabel3.setText("Permanent  Address :-");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(30, 180, 150, 14);

        jLabel4.setText("Phone Number :-");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(30, 330, 120, 30);

        jLabel13.setText("Mobile Number :-");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(30, 380, 110, 30);
        jPanel7.add(jTextField1);
        jTextField1.setBounds(150, 330, 200, 30);
        jPanel7.add(jTextField6);
        jTextField6.setBounds(150, 380, 200, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 320, 100);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(30, 210, 320, 100);

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 172, 392, 430));

        jButton3.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 643, 144, 38));

        jButton1.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 643, 144, 38));

        jButton2.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 643, 144, 38));

        jButton4.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 643, 144, 39));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 713, 891, 15));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 80, 891, 15));

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton3jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3jRadioButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int y=JOptionPane.showConfirmDialog(null,"Are you sure you want to update this record from the table?");
if(y==JOptionPane.YES_OPTION)
{
    {
            String s1;
{
if(jCheckBox3.isSelected()==true)
    s1="Public";
else
    s1="Staff";
}
System.out.println(s1);
String s2;
{
    if(jRadioButton3.isSelected()==true)
        s2="Male";
    else
        s2="Female";
}
System.out.println(s2);
String s3;
{
    if(jRadioButton5.isSelected()==true)
        s3="Married";
    else
        s3="Unmarried";
}
System.out.println(s3);
String s4=(String)jComboBox1.getSelectedItem();
System.out.println(s4);
String s5=(String)jTextArea1.getText();
System.out.println(s5);
String s6=(String)jTextArea2.getText();
System.out.println(s6);
        try{
            Class.forName("java.sql.Driver");
            System.out.println("E1");
    Connection cont=DriverManager.getConnection("jdbc:mysql://localhost/suraj","root","tiger");
    System.out.println("E2");
    Statement stat=cont.createStatement();
    System.out.println("E3");
    String query="insert into project1 values"
            + "(\'"+s1+"\',\'"+
            jTextField2.getText()+"\'"+",\'"
            +s2+"\',\'"+
            jTextField3.getText()+"\',\'"+
            jTextField4.getText()+"\',\'"+
            jTextField5.getText()+"\',\'"+
            s3+"\',\'"+
            s4+"\',\'"+
            s5+"\',\'"+
            s6+"\',"+
            Integer.parseInt(jTextField1.getText())+
            ","+Integer.parseInt(jTextField6.getText())+");";
    System.out.println("E4");
    stat.executeUpdate(query);
    System.out.println("E5");
    stat.close();
    cont.close();
    System.out.println("E6");
        JOptionPane.showMessageDialog(this,"Account Updated Successfully!");
        }
        catch(Exception x){
            JOptionPane.showMessageDialog(this,"Error in connectivity!");
        }

        }
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextArea1.setText(null);
        jTextArea2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
C_MainForm objy=new C_MainForm();
objy.setVisible(true);
this.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAnAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAnAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAnAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAnAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateAnAcc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
